module.exports = {
  "FailedOperation.ArrearsError": "帐号已欠费。",
  "FailedOperation.CountLimitError": "	今日次数达到限制。",
  "FailedOperation.DetectFailed": "	检测失败。",
  "FailedOperation.DownLoadError": "文件下载失败。",
  "FailedOperation.EmptyImageError": "	图片内容为空。",
  "FailedOperation.EngineRecognizeTimeout": "	引擎识别超时。",
  "FailedOperation.IdCardInfoIllegal": "身份证信息不合法（身份证号、姓名字段校验非法等）。",
  "FailedOperation.ImageBlur": "	图片模糊。",
  "FailedOperation.ImageDecodeFailed": "	图片解码失败。",
  "FailedOperation.ImageNoBusinessCard": "照片未检测到名片。",
  "FailedOperation.ImageNoIdCard": "	图片中未检测到身份证。",
  "FailedOperation.ImageNoText": "	图片中未检测到文本。",
  "FailedOperation.ImageSizeTooLarge": "	图片尺寸过大，请参考输出参数中关于图片大小限制的说明。",
  "FailedOperation.InvoiceMismatch": "	发票数据不一致。",
  "FailedOperation.LanguageNotSupport": "	输入的Language不支持。",
  "FailedOperation.MultiCardError": "	照片中存在多张卡。",
  "FailedOperation.NoHKIDCard": "	非香港身份证。",
  "FailedOperation.OcrFailed": "OCR识别失败。",
  "FailedOperation.QueryNoRecord": "	查询无记录。",
  "FailedOperation.UnKnowError": "	未知错误。",
  "FailedOperation.UnOpenError": "服务未开通。",
  "InvalidParameter.ConfigFormatError": "Config不是有效的JSON格式。",
  "InvalidParameter.EngineImageDecodeFailed": "	图片解码失败。",
  "InvalidParameter.InvalidGTINError": "	无效的GTIN。",
  "InvalidParameterValue.InvalidParameterValueLimit": "	参数值错误。",
  "LimitExceeded.TooLargeFileError": "文件内容太大。",
  "ResourceNotFound.NoInvoice": "	发票不存在。",
  "ResourcesSoldOut.ChargeStatusException": "计费状态异常。",

  "ActionOffline": "	接口已下线。",
  "AuthFailure.InvalidAuthorization": "	请求头部的 Authorization 不符合腾讯云标准。",
  "AuthFailure.InvalidSecretId": "	密钥非法（不是云 API 密钥类型）。",
  "AuthFailure.MFAFailure": "	MFA 错误。",
  "AuthFailure.SecretIdNotFound": "	密钥不存在。请在控制台检查密钥是否已被删除或者禁用，如状态正常，请检查密钥是否填写正确，注意前后不得有空格。",
  "AuthFailure.SignatureExpire": "	签名过期。Timestamp 和服务器时间相差不得超过五分钟，请检查本地时间是否和标准时间同步。",
  "AuthFailure.SignatureFailure": "	签名错误。签名计算错误，请对照调用方式中的签名方法文档检查签名计算过程。",
  "AuthFailure.TokenFailure	token": " 错误。",
  "AuthFailure.UnauthorizedOperation": "	请求未授权。请参考 CAM 文档对鉴权的说明。",
  "DryRunOperation": "	DryRun 操作，代表请求将会是成功的，只是多传了 DryRun 参数。",
  "FailedOperation": "	操作失败。",
  "InternalError": "	内部错误。",
  "InvalidAction": "	接口不存在。",
  "InvalidParameter": "	参数错误（包括参数格式、类型等错误）。",
  "InvalidParameterValue": "	参数取值错误。",
  "InvalidRequest": "	请求 body 的 multipart 格式错误。",
  "LimitExceeded": "	超过配额限制。",
  "MissingParameter": "	缺少参数。",
  "NoSuchProduct": "	产品不存在",
  "NoSuchVersion": "	接口版本不存在。",
  "RequestLimitExceeded": "	请求的次数超过了频率限制。",
  "RequestSizeLimitExceeded": "	请求包超过限制大小。",
  "ResourceInUse": "	资源被占用。",
  "ResourceInsufficient": "	资源不足。",
  "ResourceNotFound": "	资源不存在。",
  "ResourceUnavailable": "	资源不可用。",
  "ServiceUnavailable": "	当前服务暂时不可用。",
  "UnauthorizedOperation": "	未授权操作。",
  "UnknownParameter": "	未知参数错误，用户多传未定义的参数会导致错误。",
  "UnsupportedOperation": "	操作不支持。",
  "UnsupportedProtocol": "	http(s) 请求协议错误，只支持 GET 和 POST 请求。",
  "UnsupportedRegion": "	接口不支持所传地域。",
}